import Foundation
import IntatisCore
import IntatisProtocol
import IntatisTools

public struct KnowledgeBaseHandle: RawRepresentable, Codable, Equatable, Hashable, Sendable {
    public let rawValue: String

    public init?(rawValue: String) {
        guard rawValue.range(
            of: #"^kb_[a-f0-9]{32}$"#,
            options: .regularExpression) != nil else {
            return nil
        }
        self.rawValue = rawValue
    }

    fileprivate static func make() -> KnowledgeBaseHandle {
        // UUID bytes are generated by the host and are never interpreted as a
        // store, path, capability, or snapshot identifier.
        KnowledgeBaseHandle(
            rawValue: "kb_" + UUID().uuidString
                .replacingOccurrences(of: "-", with: "")
                .lowercased())!
    }
}

/// Exact host scope bound to a mounted handle. A handle remains only a name:
/// each query reconstructs this value from the invocation's resolved
/// authorization and must compare equal before a reader lease is admitted.
public struct KnowledgeMountAuthority: Equatable, Hashable, Sendable {
    public let sessionID: SessionID
    public let agentID: AgentID
    public let taskID: TaskID?
    public let capabilityLeaseID: CapabilityLeaseID
    public let workspaceLeaseID: WorkspaceLeaseID
    public let workspaceRootIdentity: WorkspaceRootIdentity

    public init(sessionID: SessionID,
                agentID: AgentID,
                taskID: TaskID?,
                capabilityLeaseID: CapabilityLeaseID,
                workspaceLeaseID: WorkspaceLeaseID,
                workspaceRootIdentity: WorkspaceRootIdentity) {
        self.sessionID = sessionID
        self.agentID = agentID
        self.taskID = taskID
        self.capabilityLeaseID = capabilityLeaseID
        self.workspaceLeaseID = workspaceLeaseID
        self.workspaceRootIdentity = workspaceRootIdentity
    }

    /// Builds the query authority only from an already resolved, immutable
    /// authorization snapshot plus the executor's exact workspace lease.
    public static func searchExecution(
        authorization: ResolvedToolAuthorization,
        workspaceLease: WorkspaceLease
    ) throws -> KnowledgeMountAuthority {
        guard authorization.membership == .granted,
              authorization.toolName == "search_knowledge",
              authorization.requiredCapabilities.contains(.searchKnowledge),
              let sessionID = authorization.sessionID,
              let agentID = authorization.agent,
              let capabilityLeaseID = authorization.capabilityLeaseID,
              authorization.workspaceLeaseID == workspaceLease.id,
              authorization.workspaceRootIdentity == workspaceLease.rootIdentity,
              let workspaceRootIdentity = workspaceLease.rootIdentity,
              workspaceRootIdentity.matchesCurrentDirectory(
                rootPath: workspaceLease.rootPath) else {
            throw KnowledgeDomainError(
                .accessDenied,
                "Knowledge query authorization does not match the active host scope.")
        }
        return KnowledgeMountAuthority(
            sessionID: sessionID,
            agentID: agentID,
            taskID: authorization.taskID,
            capabilityLeaseID: capabilityLeaseID,
            workspaceLeaseID: workspaceLease.id,
            workspaceRootIdentity: workspaceRootIdentity)
    }
}

public struct KnowledgeMountedSnapshotBinding: Equatable, Sendable {
    public let handle: KnowledgeBaseHandle
    public let storeID: String
    public let storePointerRevision: Int
    public let admissionKind: KnowledgeSnapshotAdmissionKind
    public let knowledgeBaseRevision: String
    public let snapshotID: String
    public let snapshotRevision: String
    public let backendRegistryDigest: String

    public var knowledgeBaseHandle: String { handle.rawValue }
}

public struct KnowledgeUrgentPurgeResult: Equatable, Sendable {
    public let storeID: String
    public let requestedSnapshotIDs: [String]
    public let removedSnapshotIDs: [String]
    public let invalidatedReceiptCount: Int
}

/// Query-owned access to one exact validated snapshot. The underlying shared
/// snapshot lock drains before GC, and `verifyStable()` is intended to be
/// called again after retrieval/evidence construction before returning data.
public final class KnowledgeMountedSnapshotAccess: @unchecked Sendable {
    public let binding: KnowledgeMountedSnapshotBinding
    public let validatedSnapshot: KnowledgeValidatedSnapshot

    public var knowledgeBaseHandle: String { binding.handle.rawValue }

    private let token: UUID
    private let state: KnowledgeMountedAccessState
    private let releaseRegistration: @Sendable (UUID) async -> Void

    fileprivate init(binding: KnowledgeMountedSnapshotBinding,
                     validatedSnapshot: KnowledgeValidatedSnapshot,
                     readerLease: KnowledgeSnapshotReaderLease,
                     token: UUID,
                     releaseRegistration: @escaping @Sendable (UUID) async -> Void) {
        self.binding = binding
        self.validatedSnapshot = validatedSnapshot
        self.token = token
        state = KnowledgeMountedAccessState(readerLease: readerLease)
        self.releaseRegistration = releaseRegistration
    }

    public func verifyStable() throws {
        try state.verifyStable()
    }

    public func close() async {
        guard let reader = state.takeReaderLease() else { return }
        reader.release()
        await releaseRegistration(token)
    }

    deinit {
        guard let reader = state.takeReaderLease() else { return }
        reader.release()
        let releaseRegistration = releaseRegistration
        let token = token
        Task {
            await releaseRegistration(token)
        }
    }
}

private final class KnowledgeMountedAccessState: @unchecked Sendable {
    private let lock = NSLock()
    private var readerLease: KnowledgeSnapshotReaderLease?

    init(readerLease: KnowledgeSnapshotReaderLease) {
        self.readerLease = readerLease
    }

    func verifyStable() throws {
        lock.lock()
        defer { lock.unlock() }
        guard let readerLease else {
            throw KnowledgeDomainError(
                .revisionChanged,
                retryable: true,
                "Knowledge snapshot access is no longer active.")
        }
        try readerLease.verifyStable()
    }

    func takeReaderLease() -> KnowledgeSnapshotReaderLease? {
        lock.lock()
        defer { lock.unlock() }
        let active = readerLease
        readerLease = nil
        return active
    }
}

/// Process-local host admission registry. On-disk reader locks provide the
/// cross-process drain boundary; this actor adds opaque handles, exact caller
/// scope, cancellation, and ordinary/urgent revocation semantics.
public actor KnowledgeMountRegistry {
    public typealias SnapshotValidator = @Sendable (
        _ root: URL,
        _ mode: KnowledgeValidationMode,
        _ policy: KnowledgeValidationPolicy,
        _ workspaceLease: WorkspaceLease
    ) throws -> KnowledgeValidatedSnapshot

    private struct Entry: Sendable {
        let store: KnowledgeSnapshotStore
        let authority: KnowledgeMountAuthority
        let binding: KnowledgeMountedSnapshotBinding
        var admitting: Bool
    }

    private struct ActiveAccess: Sendable {
        let handle: KnowledgeBaseHandle
        let storeID: String
        let snapshotID: String
        let cancel: @Sendable () -> Void
    }

    private let policy: KnowledgeValidationPolicy
    private let validate: SnapshotValidator
    private var entries: [KnowledgeBaseHandle: Entry] = [:]
    private var activeAccess: [UUID: ActiveAccess] = [:]

    public init(validator: KnowledgeValidator,
                policy: KnowledgeValidationPolicy) {
        self.policy = policy
        validate = { root, mode, policy, workspaceLease in
            try validator.validateSnapshot(
                at: root,
                mode: mode,
                policy: policy,
                workspaceLease: workspaceLease)
        }
    }

    /// Test/custom-host seam. Shipping callers should use the concrete
    /// deterministic validator initializer above.
    public init(policy: KnowledgeValidationPolicy,
                validate: @escaping SnapshotValidator) {
        self.policy = policy
        self.validate = validate
    }

    @discardableResult
    public func mount(store: KnowledgeSnapshotStore,
                      authority: KnowledgeMountAuthority) throws
        -> KnowledgeMountedSnapshotBinding {
        try Self.validateAuthority(authority, for: store)
        let reader = try store.acquireCurrentReaderLease(
            holdStoreAdmissionThroughValidation: true)
        do {
            let snapshot = try validate(
                reader.snapshotRoot,
                .mount,
                policy,
                store.managedContentWorkspaceLease)
            try Self.validate(
                reader: reader,
                snapshot: snapshot)
            var handle = KnowledgeBaseHandle.make()
            while entries[handle] != nil {
                handle = KnowledgeBaseHandle.make()
            }
            let binding = Self.binding(
                handle: handle,
                reader: reader,
                snapshot: snapshot)
            entries[handle] = Entry(
                store: store,
                authority: authority,
                binding: binding,
                admitting: true)
            reader.release()
            return binding
        } catch {
            reader.release()
            throw error
        }
    }

    /// Explicit host-only A/B admission. Model arguments never choose these
    /// identities; the host supplies an exact validated retained snapshot.
    @discardableResult
    public func mountExactSnapshot(
        store: KnowledgeSnapshotStore,
        snapshotID: String,
        snapshotRevision: String,
        authority: KnowledgeMountAuthority
    ) throws -> KnowledgeMountedSnapshotBinding {
        try Self.validateAuthority(authority, for: store)
        let pointer = try store.loadCurrentPointer()
        let reader = try store.acquireExplicitSnapshotReaderLease(
            storeID: pointer.storeID,
            snapshotID: snapshotID,
            snapshotRevision: snapshotRevision,
            holdStoreAdmissionThroughValidation: true)
        do {
            let snapshot = try validate(
                reader.snapshotRoot,
                .mount,
                policy,
                store.managedContentWorkspaceLease)
            try Self.validate(reader: reader, snapshot: snapshot)
            var handle = KnowledgeBaseHandle.make()
            while entries[handle] != nil {
                handle = KnowledgeBaseHandle.make()
            }
            let binding = Self.binding(
                handle: handle,
                reader: reader,
                snapshot: snapshot)
            entries[handle] = Entry(
                store: store,
                authority: authority,
                binding: binding,
                admitting: true)
            reader.release()
            return binding
        } catch {
            reader.release()
            throw error
        }
    }

    public func checkout(
        handle: KnowledgeBaseHandle,
        authority: KnowledgeMountAuthority,
        cancellation: @escaping @Sendable () -> Void = {}
    ) throws -> KnowledgeMountedSnapshotAccess {
        guard var entry = entries[handle], entry.admitting else {
            throw KnowledgeDomainError(.accessDenied, "Knowledge base handle is unavailable for this caller.")
        }
        guard entry.authority == authority else {
            throw KnowledgeDomainError(.accessDenied, "Knowledge base handle is unavailable for this caller.")
        }
        try Self.validateAuthority(authority, for: entry.store)

        let reader: KnowledgeSnapshotReaderLease
        switch entry.binding.admissionKind {
        case .current:
            reader = try entry.store.acquireCurrentReaderLease(
                holdStoreAdmissionThroughValidation: true)
        case .explicitExact:
            reader = try entry.store.acquireExplicitSnapshotReaderLease(
                storeID: entry.binding.storeID,
                snapshotID: entry.binding.snapshotID,
                snapshotRevision: entry.binding.snapshotRevision,
                holdStoreAdmissionThroughValidation: true)
        }
        do {
            guard reader.pointer.storeID == entry.binding.storeID,
                  reader.pointer.revision == entry.binding.storePointerRevision,
                  reader.admissionKind == entry.binding.admissionKind,
                  reader.admittedSnapshotID == entry.binding.snapshotID,
                  reader.admittedSnapshotRevision == entry.binding.snapshotRevision else {
                entry.admitting = false
                entries[handle] = entry
                throw KnowledgeDomainError(
                    .revisionChanged,
                    retryable: true,
                    "Knowledge base handle was replaced and must be mounted again.")
            }
            let snapshot = try validate(
                reader.snapshotRoot,
                .mount,
                policy,
                entry.store.managedContentWorkspaceLease)
            try Self.validate(reader: reader, snapshot: snapshot)
            let binding = Self.binding(
                handle: handle,
                reader: reader,
                snapshot: snapshot)
            guard binding == entry.binding else {
                entry.admitting = false
                entries[handle] = entry
                throw KnowledgeDomainError(
                    .revisionChanged,
                    retryable: true,
                    "Knowledge base handle validation binding changed.")
            }

            let token = UUID()
            activeAccess[token] = ActiveAccess(
                handle: handle,
                storeID: binding.storeID,
                snapshotID: binding.snapshotID,
                cancel: cancellation)
            reader.completeAdmission()
            return KnowledgeMountedSnapshotAccess(
                binding: binding,
                validatedSnapshot: snapshot,
                readerLease: reader,
                token: token,
                releaseRegistration: { [weak self] token in
                    await self?.release(token: token)
                })
        } catch {
            reader.release()
            throw error
        }
    }

    /// Final-answer grounding replay owned by the exact mounted registration.
    /// It reopens the handle through the same host authority and pointer
    /// generation, reconstructs the frozen evidence type, and runs the exact
    /// Validator/backend registry again immediately before final commit.
    public func revalidateGroundingEvidence(
        _ grounding: ToolGroundingEvidence
    ) async throws {
        guard grounding.toolName == "search_knowledge",
              let handle = KnowledgeBaseHandle(
                rawValue: grounding.knowledgeBase),
              let entry = entries[handle],
              entry.admitting,
              entry.binding.knowledgeBaseRevision
                == grounding.knowledgeBaseRevision,
              entry.binding.snapshotID == grounding.retrievalSnapshot,
              entry.binding.snapshotRevision
                == grounding.retrievalSnapshotRevision else {
            throw KnowledgeDomainError(
                .revisionChanged,
                retryable: true,
                "Grounding handle or snapshot binding changed before final validation.")
        }
        let access = try checkout(
            handle: handle,
            authority: entry.authority)
        do {
            guard access.binding == entry.binding,
                  access.validatedSnapshot.backendRegistryDigest
                    == entry.binding.backendRegistryDigest else {
                throw KnowledgeDomainError(
                    .integrityFailed,
                    "Grounding backend registry binding changed before final validation.")
            }
            let evidence = try KnowledgeJSON.decode(
                KnowledgeSearchEvidence.self,
                from: KnowledgeJSON.encode(
                    grounding.structuredEvidence))
            guard evidence.evidenceID == grounding.evidenceID,
                  evidence.textSha256 == grounding.textSHA256,
                  evidence.evidenceURI == grounding.evidenceURI else {
                throw KnowledgeDomainError(
                    .integrityFailed,
                    "Grounding evidence identity changed before final validation.")
            }
            let validator = try access.validatedSnapshot
                .evidenceValidationContext.makeValidator()
            try validator.validateEvidence(
                evidence,
                in: access.validatedSnapshot)
            try access.verifyStable()
            await access.close()
        } catch {
            await access.close()
            throw error
        }
    }

    /// Convenience for model-authored raw handle strings. Invalid shape and
    /// unknown handles share the same non-enumerating access-denied result.
    public func checkout(
        rawHandle: String,
        authority: KnowledgeMountAuthority,
        cancellation: @escaping @Sendable () -> Void = {}
    ) throws -> KnowledgeMountedSnapshotAccess {
        guard let handle = KnowledgeBaseHandle(rawValue: rawHandle) else {
            throw KnowledgeDomainError(.accessDenied, "Knowledge base handle is unavailable for this caller.")
        }
        return try checkout(
            handle: handle,
            authority: authority,
            cancellation: cancellation)
    }

    public func revoke(_ handle: KnowledgeBaseHandle,
                       cancelActive: Bool = false) {
        if var entry = entries[handle] {
            entry.admitting = false
            entries[handle] = entry
        }
        if cancelActive {
            for access in activeAccess.values where access.handle == handle {
                access.cancel()
            }
        }
    }

    public func revokeStore(storeID: String,
                            cancelActive: Bool = false) {
        let handles = entries.values
            .filter { $0.binding.storeID == storeID }
            .map(\.binding.handle)
        for handle in handles {
            revoke(handle, cancelActive: cancelActive)
        }
    }

    /// Revokes one opaque handle, signals every query admitted through that
    /// handle, and waits for their query-owned reader leases to drain. Other
    /// handles for the same store remain independent.
    public func revokeAndDrain(
        _ handle: KnowledgeBaseHandle,
        timeoutNanoseconds: UInt64 = 5_000_000_000
    ) async -> Bool {
        revoke(handle, cancelActive: true)
        let start = DispatchTime.now().uptimeNanoseconds
        while activeAccess.values.contains(where: { $0.handle == handle }) {
            let elapsed = DispatchTime.now().uptimeNanoseconds &- start
            if elapsed >= timeoutNanoseconds { return false }
            do {
                try await Task.sleep(
                    nanoseconds: min(
                        10_000_000,
                        timeoutNanoseconds - elapsed))
            } catch {
                return false
            }
        }
        entries.removeValue(forKey: handle)
        return true
    }

    /// Marks handles stale as soon as their exact pointer binding is no longer
    /// current. Existing accesses keep their reader leases; only new admission
    /// is revoked.
    public func invalidateReplacedHandles(for store: KnowledgeSnapshotStore) throws {
        let pointer = try store.loadCurrentPointer()
        for (handle, var entry) in entries where
            entry.store.storeRootIdentity == store.storeRootIdentity
        {
            let currentBindingStillMatches =
                entry.binding.admissionKind == .explicitExact
                || (entry.binding.snapshotID == pointer.currentSnapshot
                    && entry.binding.snapshotRevision == pointer.currentSnapshotRevision)
            guard entry.binding.storeID == pointer.storeID,
                  entry.binding.storePointerRevision == pointer.revision,
                  currentBindingStillMatches else {
                entry.admitting = false
                entries[handle] = entry
                continue
            }
        }
    }

    /// Urgent-purge admission boundary: revoke, signal every active query, and
    /// wait for their process-local registrations to drain. The store's
    /// per-snapshot exclusive lock remains the final cross-process proof.
    public func revokeStoreAndDrain(
        storeID: String,
        timeoutNanoseconds: UInt64 = 5_000_000_000
    ) async -> Bool {
        revokeStore(storeID: storeID, cancelActive: true)
        let start = DispatchTime.now().uptimeNanoseconds
        while activeAccess.values.contains(where: { $0.storeID == storeID }) {
            let elapsed = DispatchTime.now().uptimeNanoseconds &- start
            if elapsed >= timeoutNanoseconds { return false }
            do {
                try await Task.sleep(nanoseconds: min(10_000_000, timeoutNanoseconds - elapsed))
            } catch {
                return false
            }
        }
        return true
    }

    /// Complete sensitive-content purge boundary for the active Intatis store:
    /// close admission, cancel and drain local queries, acquire the exact store
    /// writer, persistently remove the current pointer when it is in scope,
    /// invalidate concrete host receipts, then remove snapshots whose
    /// cross-process reader locks have drained.
    public func urgentPurge(
        storeID: String,
        snapshotIDs: Set<String>,
        receiptStore: KnowledgeValidationReceiptStore,
        timeoutNanoseconds: UInt64 = 5_000_000_000
    ) async throws -> KnowledgeUrgentPurgeResult {
        guard KnowledgeStoreIdentifier.isValidStoreID(storeID),
              !snapshotIDs.isEmpty,
              snapshotIDs.allSatisfy(KnowledgeStoreIdentifier.isValidSnapshotID) else {
            throw KnowledgeDomainError(.profileInvalid, "Urgent knowledge purge scope is invalid.")
        }
        let matchingStores = entries.values
            .filter { $0.binding.storeID == storeID }
            .map(\.store)
        guard let store = matchingStores.first,
              matchingStores.allSatisfy({
                $0.storeRootIdentity == store.storeRootIdentity
                    && $0.workspaceLeaseID == store.workspaceLeaseID
              }) else {
            throw KnowledgeDomainError(.accessDenied, "Urgent knowledge purge store is not mounted in one exact host scope.")
        }

        let start = DispatchTime.now().uptimeNanoseconds
        guard await revokeStoreAndDrain(
            storeID: storeID,
            timeoutNanoseconds: timeoutNanoseconds) else {
            throw KnowledgeDomainError(
                .searchTimeout,
                retryable: true,
                "Urgent knowledge purge timed out while draining active queries.")
        }

        var writer: KnowledgeStoreWriterLease?
        while writer == nil {
            writer = try store.tryAcquireWriterLease()
            if writer != nil { break }
            let elapsed = DispatchTime.now().uptimeNanoseconds &- start
            guard elapsed < timeoutNanoseconds else {
                throw KnowledgeDomainError(
                    .searchTimeout,
                    retryable: true,
                    "Urgent knowledge purge timed out waiting for the store writer.")
            }
            do {
                try await Task.sleep(
                    nanoseconds: min(10_000_000, timeoutNanoseconds - elapsed))
            } catch {
                throw KnowledgeDomainError(.searchCancelled, "Urgent knowledge purge was cancelled.")
            }
        }
        guard let writer else {
            throw KnowledgeDomainError(.internalError, "Urgent knowledge purge writer admission failed.")
        }
        defer { writer.release() }

        let pointer = try writer.currentPointer()
        if let current = pointer?.currentSnapshot,
           snapshotIDs.contains(current) {
            _ = try writer.deactivateStorePointer(
                expectedStoreID: storeID)
        }

        let invalidated = try receiptStore.invalidate(
            storeID: storeID,
            snapshotIDs: snapshotIDs,
            preventRepublication: true)
        let removed = try writer.purgeDrainedSnapshots(snapshotIDs)
        entries = entries.filter { _, entry in
            entry.binding.storeID != storeID
        }
        return KnowledgeUrgentPurgeResult(
            storeID: storeID,
            requestedSnapshotIDs: snapshotIDs.sorted(),
            removedSnapshotIDs: removed.sorted(),
            invalidatedReceiptCount: invalidated)
    }

    public func activeAccessCount(for handle: KnowledgeBaseHandle) -> Int {
        activeAccess.values.filter { $0.handle == handle }.count
    }

    public func isAdmitting(_ handle: KnowledgeBaseHandle) -> Bool {
        entries[handle]?.admitting == true
    }

    private func release(token: UUID) {
        activeAccess.removeValue(forKey: token)
    }

    private static func validateAuthority(
        _ authority: KnowledgeMountAuthority,
        for store: KnowledgeSnapshotStore
    ) throws {
        guard authority.workspaceLeaseID == store.workspaceLeaseID,
              authority.workspaceRootIdentity == store.workspaceRootIdentity,
              authority.workspaceRootIdentity.matchesCurrentDirectory(
                rootPath: store.workspaceLease.rootPath) else {
            throw KnowledgeDomainError(.accessDenied, "Knowledge mount authority does not match the active workspace.")
        }
    }

    private static func validate(
        reader: KnowledgeSnapshotReaderLease,
        snapshot: KnowledgeValidatedSnapshot
    ) throws {
        guard reader.snapshotRootIdentity == snapshot.rootIdentity,
              reader.pointer.storeID == snapshot.profile.bundle.id,
              reader.admittedSnapshotID == snapshot.profile.retrievalSnapshot.id,
              reader.admittedSnapshotRevision
                == snapshot.profile.retrievalSnapshot.revision,
              snapshot.profile.retrievalSnapshot.bundleRevision
                == snapshot.profile.bundle.revision,
              snapshot.report.semanticVerdict else {
            throw KnowledgeDomainError(
                .integrityFailed,
                "Knowledge store pointer and validated snapshot binding disagree.")
        }
        try reader.verifyStable()
    }

    private static func binding(
        handle: KnowledgeBaseHandle,
        reader: KnowledgeSnapshotReaderLease,
        snapshot: KnowledgeValidatedSnapshot
    ) -> KnowledgeMountedSnapshotBinding {
        KnowledgeMountedSnapshotBinding(
            handle: handle,
            storeID: reader.pointer.storeID,
            storePointerRevision: reader.pointer.revision,
            admissionKind: reader.admissionKind,
            knowledgeBaseRevision: snapshot.profile.bundle.revision,
            snapshotID: reader.admittedSnapshotID,
            snapshotRevision: reader.admittedSnapshotRevision,
            backendRegistryDigest: snapshot.backendRegistryDigest)
    }
}
